### ISSUE TITLE
configure: error: Missing required program 'setfacl': ensure it is installed and on PATH.

### ISSUE THREAD

**Issue by ernesto418** [tpm2dev/tpm.dev.docker#4]
Hello,

While building the image, in the comand:
`./configure --with-udevrulesprefix`
 I found a problem:
`configure: error: Missing required program 'setfacl': ensure it is installed and on PATH.`

It can be solved by adding the package "asl" in the installation commands in Dockerfile.release (line 112)

**Comment by tomoveu** [comment]
Hi @ernesto418 Thank you for catching this :raised_hands: 

This might be related to the Docker version. I will make sure to add "asl" in the Docker.release file, so we have maximum compliance.
